export const FIRST_NAME = 'Hanna'
export const LAST_NAME = 'Gaudasińska-Zapaśnik'
export const JOB_TITLE = 'Web developer'

export const LOCATION = 'Warsaw'
export const EMAIL = 'hgz.devi@gmail.com'
export const WWW = 'https://hgzdev.github.io/cv'
export const GITHUB = 'https://github.com/HGZdev'
export const TEL = '+48 506 042 937'
export const LINKEDIN = 'https://www.linkedin.com/in/hanna-gaudasinska-zapasnik'
