export {default as Intro} from './Intro'
export {default as About} from './About'
export {default as Skills} from './Skills'
export {default as Portfolio} from './Portfolio'
export {default as Experience} from './Experience'
